---
- hosts: all
  become: yes
  vars:
     backuppc_user: "admin"
     backuppc_password: "admin"

  tasks:
  - name: Cheack and Print Linux Version
    debug: var=ansible_os_family

  - name: Install "backuppc from repository" package
    apt:
     name: backuppc 
     state: present

  - name: Add config backuppc 
    template:
       src: ./backuppc.conf.j2
       dest: /etc/backuppc/apache.conf
    notify: Restart backuppc.service

  - name: Make sure we can use htpasswd module
    apt: 
      name: python3-passlib
      state: present

  - name: Add a user to a password file and ensure permissions are set
    community.general.htpasswd:
      path: /etc/backuppc/htpasswd
      name: "{{ backuppc_user }}"
      password: "{{ backuppc_password }}"
      owner: backuppc
      group: www-data
      mode: 0640

  handlers:
  - name: Restart backuppc.service
    service: name=backuppc.service state=restarted
  - name: Restart backuppc.service
    service: name=apache2.service state=restarted

