---
- name: ovs-config
  hosts: all
  become: yes
  vars:
     source_file_faucet: ./faucet
     destin_file_faucet: /etc/faucet/faucet.yaml
     source_file_faucet1: ./acls
     destin_file_faucet1: /etc/faucet/acls.yaml
     
  tasks:
  - name: Copy file faucet to Server
    copy: src={{ source_file_faucet }} dest={{ destin_file_faucet }} mode=0640 owner=root group=root backup=yes
 
  - name: Copy file faucet1 to Server
    copy: src={{ source_file_faucet1 }} dest={{ destin_file_faucet1 }} mode=0640 owner=root group=root backup=yes
 

  - name: Remove network ovsbr0
    openvswitch_bridge:
      bridge: ovsbr0
      state: absent
    
  - name: Add new network ovsbr0
    openvswitch.openvswitch.openvswitch_bridge:
      bridge: ovsbr0
      state: present
    
  - name: Add parametrs ovsbr0
    shell: |
      ovs-vsctl set bridge ovsbr0 other-config:datapath-id=0000000000000001
      #ovs-vsctl set-fail-mode ovsbr0 secure
      ovs-vsctl set bridge ovsbr0 protocols=OpenFlow13,OpenFlow10
      ovs-vsctl set-controller ovsbr0 tcp:127.0.0.1:6653 tcp:127.0.0.1:6654
      
  - name: Add port for ovsbr0
    openvswitch.openvswitch.openvswitch_port:
      bridge: ovsbr0
      port: ens4
      state: present
      set: Interface ens4 ofport_request=4 
  
  - name: Add port for ovsbr0
    openvswitch.openvswitch.openvswitch_port:
      bridge: ovsbr0
      port: ens5
      state: present
      set: Interface ens5 ofport_request=5
      
  - name: Add port for ovsbr0
    openvswitch.openvswitch.openvswitch_port:
      bridge: ovsbr0
      port: ens6
      state: present
      set: Interface ens6 ofport_request=6

  - name: Restart faucet.service
    service: name=faucet.service state=restarted
    
  - name: Restart gauge.service
    service: name=gauge.service state=restarted  
    
  - name: Restart grafana-server.service
    service: name=grafana-server.service state=restarted 
    
  - name: Restart prometheus.service
    service: name=prometheus.service state=restarted     
    