---
- hosts: all
  become: yes
  
  tasks:
  - name: Cheack and Print Linux Version
    debug: var=ansible_os_family

  - name: Add config nginx.service 
    template:
       src: ./default.conf.j2
       dest: /etc/nginx/sites-enabled/default
    notify: Restart nginx.service  

  - name: Add config mariadb.service disable strict mode
    template:
       src: ./disable_strict_mode.cnf.j2
       dest: /etc/mysql/conf.d/disable_strict_mode.cnf
    notify: Restart mariadb.service 

  - name: Install a list of packages
    apt:
      pkg:
        - nginx
        - language-pack-en-base
        - php-fpm
        - mariadb-server
        - php-mysql
        - php-cli
        - php-gd
        - php-curl
        - php-xml
        - php-mbstring
        - php-intl
        - git
        - wget
      state: latest
      update_cache: True
    when: ansible_os_family == "Debian"
    
  handlers:
  - name: Restart nginx.service 
    service: name=nginx.service  state=restarted
  - name: Restart mariadb.service
    service: name=mariadb.service state=restarted
    