---
- name: install ISP
  hosts: all
  become: yes
  
  tasks:
  - name: Edit file systemd-network ens5
    template:
       src: ./config/00_ens5.network.j2
       dest: /etc/systemd/network/00_ens5.network
  
  - name: Install "bird2 from repository" package
    apt:
     name: bird2
     state: present

