---
- name: Install frr
  hosts: all
  become: yes
  
  tasks:
  - name: Install "frr from repository" package
    apt:
     name: frr
     state: present

  - name: Add  net.ipv4.ip_forward = 1 
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes

  - name: Add  net.ipv4.conf.default.rp_filter=1
    ansible.posix.sysctl:
      name: net.ipv4.conf.default.rp_filter
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
      
   - name: Add  net.ipv4.conf.all.rp_filter=1
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes   
