---
- name: Install frr
  hosts: all
  become: yes
  gather_facts: true
  vars:
  
#       noda_a: bgp1.inc
#       noda_a_ip: 10.0.0.7
#       noda_b: faucet.inc
#       noda_b_ip: 10.0.0.2
#       noda_c: clientf1.inc
#       noda_c_ip: 10.0.0.6
#       source_file_frr_daemon: ./config/daemons.j2
#       destin_file_frr_daemon: /etc/frr/daemons

       source_file_frr_a: ./config/a_frr.conf.j2
       source_file_frr_b: ./config/b_frr.conf.j2
       source_file_frr_c: ./config/c_frr.conf.j2
       destin_file_frr: /etc/frr/frr.conf
       
  tasks:
  - name: Show facts available on the system nodename
    debug:
       var: ansible_nodename 

  - name: Show facts available on the system ipv4
    debug:
       var: ansible_default_ipv4.address  

 
  - name: Install "frr from repository" package
    apt:
     name: frr
     state: present

  - name: Add  net.ipv4.ip_forward = 1 
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes

  - name: Add  net.ipv4.conf.default.rp_filter=1
    ansible.posix.sysctl:
      name: net.ipv4.conf.default.rp_filter
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
      
  - name: Add  net.ipv4.conf.all.rp_filter=1
    ansible.posix.sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes   

#  - name: Add config frr for daemon
#    template:
#       src: "{{ source_file_frr_daemon }}"
#       dest: "{{ destin_file_frr_daemon }}" 
#       mode: 0640 
#       owner: frr 
#       group: frr 
#       backup: yes       
#   notify: Restart frr.service 

  - name: Add config frr for noda_a
    template:
       src: "{{ source_file_frr_a }}"
       dest: "{{ destin_file_frr }}"
    when: ansible_nodename == "{{ noda_a }}"   
    notify: Restart frr.service 
 
  - name: Add config frr for noda_b
    template:
       src: "{{ source_file_frr_b }}"
       dest: "{{ destin_file_frr }}"
    when: ansible_nodename == "{{ noda_b }}"   
    notify: Restart frr.service 

  - name: Add config frr for noda_c
    template:
       src: "{{ source_file_frr_c }}"
       dest: "{{ destin_file_frr }}"
    when: ansible_nodename == "{{ noda_c }}"   
    notify: Restart frr.service 

    
    
  handlers:
  - name: Restart frr.service
    service: name=frr.service state=restarted      