---
- name: my like tools for debian
  hosts: all
  become: yes
  
  tasks:
  - name: Install a list of packages
    apt:
      pkg:
        - python3
        - python3-apt 
        - python3-pip 
        - python3-setuptools
        - python3-pymysql 
        - tcpdump
        - iperf3
        - virttop
        - virtinst
        - openvswitch-switch 
        - tcpdump
        - git 
        - dnsutils
        - mtr
        - iotop
        - virt-top
        - logwatch
        - postfix
        - smartmontools
        - mailutils
        - zabbix-agent        
      state: latest
      update_cache: True    