# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "generic/ubuntu1804"

  config.vm.hostname = "test.local"

  config.vm.provider "libvirt" do |domain|
    domain.memory = "2048"
    domain.cpus = "2"
   end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./ansible/install.yaml"
   end


end

