# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = "debian/buster64"

  config.vm.hostname = "zabbix5"

  config.vm.network "public_network",
      :dev => "ovsbr0",
      :ovs => "true"

  config.vm.provider "libvirt" do |domain|
    domain.memory = "1024"
    domain.cpus = "2"
   end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "install_zabbix-6.2.yaml"
   end


end

