---
- name: on ip forward
  hosts: all
  become: yes
  
  tasks:
  - name: Add net.ipv4.ip_forward = 1 
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
