---
- hosts: bind9
  become: yes
  
  tasks:
  - name: Cheack and Print Linux Version
    debug: var=ansible_os_family

  - name: Install "bind9 from repository" package
    apt:
     name: bind9
     state: present

  - name: Add config bind9 named.conf.local
    template:
       src: ./config/named.conf.local.j2
       dest: /etc/bind/named.conf.local
       owner: root
       group: bind
    notify: Restart bind9

  - name: Add config bind9 named.conf.options
    template:
       src: ./config/named.conf.options.j2
       dest: /etc/bind/named.conf.options
       owner: root
       group: bind
    notify: Restart bind9
 
  - name: Create a directory if it does not exist /etc/bind/master
    ansible.builtin.file:
      path: /etc/bind/master
      state: directory
      owner: root
      group: bind
      mode: '0755'  
  
  - name: Add config bind9 10.0.0.in-addr.arpa.zone
    template:
       src: ./config/10.0.0.in-addr.arpa.zone.j2
       dest: /etc/bind/master/10.0.0.in-addr.arpa.zone
       owner: root
       group: bind
    notify: Restart bind9
 
  - name: Add config bind9 board.inc.zone
    template:
       src: ./config/board.inc.zone.j2
       dest: /etc/bind/master/board.inc.zone
       owner: root
       group: bind
    notify: Restart bind9
 
  - name: Add config zabbix agent
    template:
       src: ./config/server-resolv.conf.j2
       dest: /etc/resolv.conf

  handlers:
  - name: Restart bind9
    service: name=bind9 state=restarted      
