---
- name: Loops Hello 
  hosts: all
  become: yes

  tasks:
  - name: Say Hello to ALL
    debug: msg="Hello {{ item }}"
    loop: 
        - "Vasya"
        - "Masha"
        - "Olga"
        - "Petr" 

  - name: loop until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2 
    retries: 10
    until: output.stdout.find("ZZZZ") == false
  
  - name: Print Final Output
    debug:
      var:  output.stdout


#  - name: Install many packeg
#    apt: name={{ item }} state=present
#    with_items: 
#            - apache2
#            - htop
#            - tree



        
...
